import {useState} from 'react';
import {signIn} from 'next-auth/react';
import {useRouter} from 'next/router';
import AuthLayout from "@/pages/components/AuthLayout";
import Head from "next/head";
import Link from "next/link";

const Login = () => {
    const [credentials, setCredentials] = useState({email: '', password: ''});
    const router = useRouter();
    const [error, setError] = useState(null);

    const handleChange = (e) => {
        setCredentials({...credentials, [e.target.name]: e.target.value});
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        setError(null); // Reset error before new request

        const result = await signIn('credentials', {
            redirect: false,
            username: credentials.email,
            password: credentials.password,
        });
        if (!result.error) {
            // Successfully signed in, redirect to the desired page
            await router.push('/');
        } else {
            // Error signing in
            console.error('Error signing in:', result.error);
            setError(result.error);
        }
    };

    return (
        <div>
            <Head>
                <title>EtherLoan - Login</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/Logo-simple.svg"/>
            </Head>

            <h1>Login</h1>
            <form onSubmit={handleSubmit}>
                <div className={"mb-4"}>
                    <label className={"form-label"} htmlFor="email">Email:</label>
                    <input className={"form-control form-input"} type="email" id="email" name="email"
                           value={credentials.email}
                           onChange={handleChange}/>
                </div>
                <div className={"mb-4"}>
                    <label className={"form-label"} htmlFor="password">Password:</label>
                    <input className={"form-control form-input"} type="password" id="password" name="password"
                           value={credentials.password}
                           onChange={handleChange}/>
                </div>
                <div className={"mb-4"}>
                    <Link className={"text-decoration-none text-white"} href="/auth/register">Don`t have an
                        account? <u>Register</u></Link>
                </div>
                <button className={"btn btn-primary w-100"} type="submit">Submit</button>
            </form>
            <div className="my-3">
                {error && <p style={{color: 'red'}}>{error}</p>}
            </div>
        </div>
    );
}

Login.getLayout = function getLayout(page) {
    return <AuthLayout>{page}</AuthLayout>;
};

export default Login;