import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";
import LoginBtn from "@/pages/components/login-btn";
import {useSession} from "next-auth/react";
import MainLayout from "./components/MainLayout"

const inter = Inter({subsets: ["latin"]});
const Home = () => {
    const {data: session, status} = useSession();
    return (
        <>
            <Head>
                <title>EtherLoan</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/Logo-simple.svg"/>
            </Head>
            <main className={`${inter.className} ${styles.main}`}>
                <pre>{JSON.stringify(session, null, 2)}</pre>
                <LoginBtn/>

                <div className="row">
                    <div className="col-md-6">
                        <p>Account Summary</p>

                    </div>
                    <div className="col-md-6">
                        Notifications

                        dsa
                    </div>
                </div>
            </main>
        </>
    );
};

Home.getLayout = function getLayout(page) {
    return <MainLayout>{page}</MainLayout>;
};

export default Home;