import Head from "next/head";
import {Inter} from "next/font/google";
import styles from "@/styles/Home.module.css";
import LoginBtn from "@/pages/components/login-btn";
import {useSession} from "next-auth/react";

const inter = Inter({subsets: ["latin"]});

export default function Home() {
    const {data: session, status} = useSession();
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={`${inter.className} ${styles.main}`}>
                page
                <pre>{JSON.stringify(session, null, 2)}</pre>
                <LoginBtn/>
            </main>
        </>
    );
}
