import Head from "next/head";
import styles from "@/styles/Home.module.css";
import {useSession} from "next-auth/react";
import MainLayout from "./components/MainLayout"
import MoneyStateCard from "@/pages/components/cards/MoneyStateCard";
import TextSideBySide from "@/pages/components/text/TextSideBySide";
import NotificationCard from "@/pages/components/cards/NotificationCard";

const Home = () => {
    const {data: session, status} = useSession();
    // if (!session) {
    //     return <>
    //         <Head>
    //             <title>EtherLoan</title>
    //             <meta name="description" content="Generated by create next app"/>
    //             <meta name="viewport" content="width=device-width, initial-scale=1"/>
    //             <link rel="icon" href="/assets/Logo-simple.svg"/>
    //         </Head>
    //         <main className={"my-5"}>
    //             <div class="row">
    //                 <div class="col-md-6">
    //                     <CardUnauthenticated></CardUnauthenticated>
    //                 </div>
    //             </div>
    //         </main>
    //     </>
    // }

    return (
        <>
            <Head>
                <title>EtherLoan</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/assets/Logo-simple.svg"/>
            </Head>
            <main className={`${styles.main}`}>
                <pre>{JSON.stringify(session, null, 2)}</pre>
                {/*<LoginBtn/>*/}

                <div className="row">
                    <div className="col-md-6">
                        <p className={"text-secondary"}>Account Summary</p>
                        <MoneyStateCard amount={1500} dollarAmount={40}/>
                        <div className={"mb-3"}>
                            <TextSideBySide text={"Money Saved"} moneyAmount={100.31}></TextSideBySide>
                            <TextSideBySide text={"Money blocked in transactions"}
                                            moneyAmount={313.11}></TextSideBySide>
                            <TextSideBySide text={"Money for subscriptions"} moneyAmount={500.31}></TextSideBySide>
                            <TextSideBySide text={"From future transactions"} moneyAmount={1232423.31}></TextSideBySide>
                            <TextSideBySide text={"Loan money"} moneyAmount={1203.31}></TextSideBySide>

                        </div>
                        <MoneyStateCard amount={1500} goal={"new car"} moneyNeeded={"293"}/>
                        <MoneyStateCard amount={1500} goal={"new car"} moneyNeeded={"293"}/>
                    </div>
                    <div className="col-md-6">
                        <p className={"text-secondary"}>Notifications</p>
                        <NotificationCard
                            href={"/assets/3DIcons/plus-dynamic-color.svg"}
                            notificationTitle={"Money Added"}
                            notificationDescription={"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus id lectus sodales consectetur. Nunc eleifend auctor augue, sed pulvinar odio tempus at."}
                        ></NotificationCard>
                        <NotificationCard
                            href={"/assets/3DIcons/at-dynamic-color.svg"}
                            notificationTitle={"Transaction in progress"}
                            notificationDescription={"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent dapibus id lectus sodales consectetur. Nunc eleifend auctor augue, sed pulvinar odio tempus at."}
                        ></NotificationCard>

                    </div>
                </div>
            </main>
        </>
    );
};

Home.getLayout = function getLayout(page) {
    return <MainLayout>{page}</MainLayout>;
};

export default Home;